// Code generated by mockery v2.20.0. DO NOT EDIT.

package handler

import mock "github.com/stretchr/testify/mock"

// MockHandlerOptions is an autogenerated mock type for the HandlerOptions type
type MockHandlerOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: opts
func (_m *MockHandlerOptions) Execute(opts *handlerOptions) {
	_m.Called(opts)
}

type mockConstructorTestingTNewMockHandlerOptions interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHandlerOptions creates a new instance of MockHandlerOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHandlerOptions(t mockConstructorTestingTNewMockHandlerOptions) *MockHandlerOptions {
	mock := &MockHandlerOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
